### ISSUE TITLE
Erico's comment after proof-reading

### ISSUE THREAD

**Issue by dongericoyu** [fsolt/meritocracy#3]

**Comment by dongericoyu** [comment]
Here are some comments I have after proof-reading the paper, most of them are in regard of typo and grammatical tense. 
1. (Rnw.file line 67) "One prominent recent study, Newman, Johnston, and Lown (2015a), argues that exposure to higher levels of local income inequality **lead** people to become more likely to reject the dominant U.S. ideology of meritocracy." 

--it should be "leads people to" rather than "lead people to"

2.(Rnw.file line 76) "Newman, Johnston, and Lown (2015a) **advanced** the argument that inequality in the United States activates class conflict, leading poorer individuals in local contexts of higher inequality to reject meritocracy and become more class conscious".

-- Here we use a past tense, yet in line 90, 109 and 129 we use present tense. I think we should be consistent: when presenting an argument of a paper, using present tense is more appropriate.  Thus, **advances**

--P.S.: unless NJL here indicates the authors rather than the paper

3.. (line 132) "First, the coefficient $\gamma_{01}$ indicates only the effect of inequality when the other variable in the interaction, **income**, takes on the value of zero"

--income here refers to a specific variable in the model, thus _income_  should be emphasized.

4.(line 291) Version 1 was drawn from 2005 and 2006 surveys that asked respondents which of two statements came closest to their own opinion: `Most people who want to get ahead can make it if they're willing to work hard'' or`Hard work and determination are no guarantee of success for most people.'' 

-- To be consistent with line 294, a comma should be added in the quotation mark:  "Most people who want to get ahead can make it if they're willing to work hard,"

5.(line 714) "Among otherwise typical people in otherwise typical contexts, those with the lowest incomes living where the context of income inequality is at the highest observed level are 20 percentage points (plus or minus 9 points) less likely to reject meritocracy than similarly low-income people living where inequality is at its lowest observed level, according to these results."

--the sentence is a little bit too long. I would rewrite it as "the predicted probability of rejecting meritocracy for those with the lowest incomes living in the context of the highest income inequality is about 20 percentage points lower, comparing to those similarly low-income people living in the context of the lowest income inequality."

**Comment by fsolt** [comment]
1. You're right, Erico, that subject-verb agreement is a good thing to keep an eye on.  Here though, the actual subject is "levels" so "lead" agrees correctly.
2. Good catch.  I agree it works better that way.  And, right, NJL always refers to the paper.  We're leaving the authors out of this as much as possible.
3. Fixed.
4. It's 294 that should change: neither needs a comma.  Done
5. Hmm.  I agree: that's a tough sentence.  Thanks for flagging it.  But once I include the confidence bounds and note that we're talking about the _observed_ range of the variable---which I'd argue are both indispensable---your version is just as long.  I've revised to move the "otherwise typical" clause to 716 and steal that line's shorter phrasing and move the "according to these results" thought to 713.  I think that helps.
