### ISSUE TITLE
Theory: Response to Reviewers' comment on the implications of the results

### ISSUE THREAD

**Issue by dongericoyu** [fsolt/meritocracy#8]
Reviewer#1's comment on the expectation of relative power theory; I suggest to adding more literature and explain that RPT does not suggest those wealthy are necessarily more likely to supporting meritocracy. This should be included in the memo (and possibly two sentences in explaining the result in the paper)

Reviewer#2's comment on (1) whether each income group becomes significantly more rejecting/accepting of meritocracy due to increases in inequality, and (2) whether significant differences BETWEEN income groups emerge as inequality increases.  Similarly, I suggest we should address these two points with RPT in the theoretical review part in discussing RPT. Probably we need to rewrite the theory part.

Verify by Kevan.

**Comment by jsong10** [comment]
Reviewer 1 writes, “I think relative power theory would predict that the wealthy would become more supportive of the belief in meritocracy as it increases, but this is not the case.” Our results suggest that only for those with the highest incomes (over $150,000), the predicted probability of rejecting meritocracy is essentially flat regardless of the level of local income inequality. For other high income groups, such as $50-75K, $75-100K, and $100-150K, the predicted probability of rejecting meritocracy consistently declines over the observed range of inequality. We think this result is still consistent with relative power theory because it is more reasonable to expect that those with the highest incomes would support meritocracy even in low-inequality contexts. In other words, because they are already the strongest supporters of meritocracy in low-inequality contexts, high-inequality contexts do not lead them to support meritocracy more than before.

@kwhudson

**Comment by jsong10** [comment]
For comments of Reviewer 2, I added some sentences in the paper. Check 0e264df834ce6d5ef806221ea5d9eaa8ac41c385.

@kwhudson

**Comment by kwhudson** [comment]
I think that what you've added in the paper helps to clarify the theoretical expectations.

The only change I might suggest is that in the section beginning with the Huber et al quote, you might change the ending of the last sentence.

You currently have "In high-inequality contexts, all individuals regardless of income will be more likely to support meritocracy than before."

"In high-inequality contexts, all individuals regardless of income will be more likely to support meritocracy than in low-inequality contexts." Might work a bit better as it's not entirely clear what the "before" means. Just a thought.

@jsong10

**Comment by kwhudson** [comment]
In the memo, I have a few suggested changes just to improve the flow of the writing.

The original:

"With regards to the explanation of results, both reviewers had concerns on its implications to the theory on inequality and public opinion. Reviewer 1 suspected the wealthy would be more supportive of the meritocracy belief as inequality increases, which it is not shown in the result. Our results suggest that only for those with the highest incomes (over \$150,000), the predicted probability of rejecting meritocracy is essentially flat regardless of the level of local income inequality. For other high income groups, such as \$50-75K, \$75-100K, and \$100-150K, the predicted probability of rejecting meritocracy consistently declines over the observed range of inequality. We think this result is still consistent with relative power theory because it is more reasonable to expect that those with the highest incomes would support meritocracy even in low-inequality contexts. In other words, because they are already the strongest supporters of meritocracy in low-inequality contexts, high-inequality contexts do not lead them to support meritocracy more than before. Reviewer 2 suggested that the authors should differentiate between (1) whether each income group becomes significantly more rejecting/accepting of meritocracy due to increases in inequality, and (2) whether significant differences BETWEEN income groups emerge as inequality increases."

My revisions:

"With regards to the explanation of results, both reviewers expressed concerns about the potential implications for theories of inequality and public opinion. Reviewer 1 suspected the wealthy would be more supportive of the meritocracy belief as inequality increases, which it is not supported by the result. Our results suggest that only for those with the highest incomes (over \$150,000),  is the predicted probability of rejecting meritocracy essentially flat regardless of the level of local income inequality. For other high income groups, such as \$50-75K, \$75-100K, and \$100-150K, the predicted probability of rejecting meritocracy consistently declines over the observed range of inequality. We think this result is consistent with relative power theory because it is more reasonable to expect that those with the highest incomes would support meritocracy even in low-inequality contexts. In other words, because they are already the strongest supporters of meritocracy in low-inequality contexts, high-inequality contexts do not lead them to support meritocracy more than before. Reviewer 2 suggested that the authors should differentiate between (1) whether each income group becomes significantly more rejecting/accepting of meritocracy due to increases in inequality, and (2) whether significant differences BETWEEN income groups emerge as inequality increases."

Additionally, It seems like this ends prematurely. You highlight the suggestion of reviewer 2, but don't address it at all. Erico had noted in the memo that after the replication was done you should maybe incorporate those results in addressing reviewer 2's comment.

@jsong10

**Comment by jsong10** [comment]
Following Kevan's comments, I revised the memo as follows.

@kwhudson 

"With regards to the explanation of results, both reviewers expressed concerns about the potential implications for theories of inequality and public opinion. Reviewer 1 suspected the wealthy would be more supportive of the meritocracy belief as inequality increases, which it is not supported by the result. Our results suggest that only for those with the highest incomes (over \$150,000), is the predicted probability of rejecting meritocracy essentially flat regardless of the level of local income inequality. For other high income groups, such as \$50-75K, \$75-100K, and \$100-150K, the predicted probability of rejecting meritocracy consistently declines over the observed range of inequality. We think this result is consistent with the relative power theory because it is more reasonable to expect that those with the highest incomes would support meritocracy even in low-inequality contexts. In other words, because they are already the strongest supporters of meritocracy in low-inequality contexts, high-inequality contexts do not lead them to support meritocracy more than before. 
Also, Reviewer 2 suggested that the authors should differentiate between (1) whether each income group becomes significantly more rejecting/accepting of meritocracy due to increases in inequality, and (2) whether significant differences BETWEEN income groups emerge as inequality increases, and should reject these two main arguments of NJL separately. Our replication results clearly reject both of them. For the first argument, our replication results suggest that low income groups become significantly "more accepting meritocracy" rather than "more rejecting meritocracy" as inequality increases. Income groups over \$50K (except over \$150K) also become more accepting meritocracy, even though they are not statistically significant (Figure 4). For the second argument, because none of income groups become significantly more rejecting meritocracy as inequality increases, the differences BETWEEN income groups diminish rather than emerge as inequality increases (Figure 5)."

**Comment by jsong10** [comment]
added to the memo. 7bd5015e3947aef3dd793f2c72cbcdd8abff4251
